Repository PrincetonUniversity/PsyNeuLink, pull requests merged in 2020-03, with the labels that each got.

#1515 github-actions: Upload test results artifacts on both success and failure
  .github/workflows/pnl-ci.yml
Labels: CI

#1521 llvm: Fix ctypes import error in printf
  psyneulink/core/llvm/helpers.py
Labels: bug, compiler

#1522 llvm: Cache generated structures
  psyneulink/core/compositions/composition.py
  psyneulink/core/llvm/builder_context.py
  psyneulink/core/llvm/jit_engine.py
Labels: compiler, feature

#1524 llvm/jit: Temporarily disable compiler optimizations.
  psyneulink/core/llvm/jit_engine.py
Labels: compiler

#1532 llvm: Add compilation support for Reduce function
  psyneulink/core/components/functions/combinationfunctions.py
  psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
  tests/functions/test_combination.py
Labels: compiler, feature

#1533 llvm: Fix controller compiled shape mismatch
  psyneulink/core/components/component.py
  psyneulink/core/components/mechanisms/modulatory/control/optimizationcontrolmechanism.py
  setup.cfg
  tests/composition/test_control.py
Labels: compiler

#1540 llvm: Fix use of parameter values in Reduce and DDM
  conftest.py
  psyneulink/core/components/functions/combinationfunctions.py
  psyneulink/core/components/functions/transferfunctions.py
  psyneulink/core/components/mechanisms/mechanism.py
  psyneulink/core/components/mechanisms/processing/transfermechanism.py
  psyneulink/core/components/ports/port.py
  psyneulink/library/components/mechanisms/modulatory/control/agt/lccontrolmechanism.py
  psyneulink/library/components/mechanisms/processing/integrator/ddm.py
  tests/functions/test_combination.py
  tests/mechanisms/test_ddm_mechanism.py
Labels: compiler

#1542 llvm, functions/DriftDiffusionAnalytical: Use abs value to check magnitude
  psyneulink/core/components/functions/distributionfunctions.py
  tests/functions/test_distribution.py
Labels: compiler
