Repository PrincetonUniversity/PsyNeuLink, pull requests merged in 2020-11, with the labels that each got.

#1815 deps: Convert leabra to 'extra' dependency
  .github/workflows/pnl-ci.yml
  .travis.yml
  leabra_requirements.txt
  setup.py
Labels: deps

#1824 Revert "deps: Convert leabra to 'extra' dependency"
  .github/workflows/pnl-ci.yml
  .travis.yml
  leabra_requirements.txt
  setup.py
Labels: CI, deps

#1828 github-actions: Restrict graphviz version on windows
  .github/workflows/pnl-ci.yml
Labels: CI
